### ISSUE TITLE
VPS providers who have used this?

### ISSUE THREAD

**Issue by dm17** [cwerling/psptool#2]
Any idea if any VPS providers have used this? Those of us with cloud instances would certainly feel better about their security from within the same datacenter with these patches on our AMD systems.

**Comment by cwerling** [comment]
Are you referring to the Secure Encrypted Virtualization by AMD? I'm not sure which patches you are referring to.

**Comment by dm17** [comment]
> Are you referring to the Secure Encrypted Virtualization by AMD? I'm not sure which patches you are referring to.

Yes, VPS that run on AMD CPUs, and have used psptool to remove the vulnerabilities.

**Comment by cwerling** [comment]
PSPTool does not by itself remove any vulnerabilities. Packing the PSP (and other subsystems') firmware into UEFI firmware is done by the BIOS or mainboard vendor who in turn receive these files from AMD as part of AGESA.
What PSPTool provides is a way to dissect UEFI firmware in order to find out specific versions, cryptographic keys and binaries of the PSP firmware.
